# docker run --rm -d -t -v /D_DRIVE:/d -p 2251:22 accs
# docker run --rm -d -t -v /D_DRIVE:/d -p 2251:22 --expose 9001-9003 --expose 9090 -p 9001:9001 -p 9002:9002 -p 9003:9003 -p 9090:9090 --privileged -v /dev/bus/usb:/dev/bus/usb --cap-add=SYS_PTRACE --security-opt seccomp=unconfined accs
# docker-compose -f D:\Projects\ACCS\accs.yml up -d
# docker-compose -f D:\Projects\ACCS\accs.yml down

version: "3.3"
services:

### ACCS
  accs:
#    image: shchohan/accs:20200220
    image: accs
    container_name: accs
    volumes:
      - /d/Projects/ACCS/bin/20200220:/ACCS
      # - /D_DRIVE:/d
    ports:
      - "2251:22"
      - "8080:9090"
      - "7963:6379"
    networks:
      - accs_net
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
        - privileged 
        - cap-add=sys_ptrace
        - security-opt seccomp=unconfined
        - TZ=America/Toronto
    tty: true
    #entrypoint: "/bin/bash -c '/start.sh && $ACCS_HOME/start_accs.sh'"
    #entrypoint: ["/start.sh"]

networks:
  accs_net:
