FROM ubuntu

RUN mkdir /var/run/sshd
RUN apt-get update && apt-get install -y openssh* vim util-linux sysvinit-utils 
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN echo 'root:screencast' | chpasswd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["service", "ssh", "start"]

# docker build -f Dockerfile_ssh -t ubuntu_sshd .
# docker run --rm -it -p 2222:22 --name ubuntu_sshd ubuntu_sshd
# docker port ubuntu_sshd 22
# docker-machine ls
# ssh -v root@192.168.99.100 -p 2222  # screencast
