#docker run --rm -d -t -v /C_DRIVE:/c -v /D_DRIVE:/d -v /E_DRIVE:/e -p 2222:22 --expose 9001-9003 --expose 9090 -p 9001:9001 -p 9002:9002 -p 9003:9003 -p 9090:9090  --privileged -v /dev/bus/usb:/dev/bus/usb --cap-add=SYS_PTRACE --security-opt seccomp=unconfined ubuntu_dev

version: "3.3"
services:

### Ubuntu_dev
# docker-compose.exe -f .\ubuntu_dev\ubuntu_dev.yml up -d ubuntu_dev
  ubuntu_dev:
    #image: shchohan/ubuntu_dev:20200612
    image: ubuntu_dev
    container_name: ubuntu_dev
    working_dir: /d/Projects/ACCS
    domainname: Salah.Chohan
    hostname: ubuntu_dev
    ipc: host
    #mac_address: 02:42:ac:11:65:43
    user: root
    privileged: true
    #read_only: true
    #shm_size: 64M
    #stdin_open: true
    #command: echo "Bismillah"
    #TZ: America/Denver    # upsupported config option. even docker is not starting
    
    volumes:
      - /C_DRIVE:/c
      - /D_DRIVE:/d
      - /E_DRIVE:/e
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "2222:22"
      - "9090:9090"
      - "8181:8080"
      - "6379:6379"
      - "80:80"
      # - "5010:5010"
      # - "9000:9000"
      # - "9002:9002"
      # - "9007:9007"
    environment:
        #TZ: "America/Denver"       // docker does not even start
        #TZ: America/Toronto    # upsupported config option. even docker is not starting
        - TZ=Asia/Shanghai  # no effect
        #- TZ=America/Toronto
        - privileged 
        - cap-add=sys_ptrace
        #- security-opt seccomp=unconfined
        - security-opt 
        - seccomp=unconfined

    networks:
      - accs_net

    tty: true
    #entrypoint: /start.sh
    #command: /start.sh

## Oracle https://github.com/fuzziebrain/docker-oracle-xe
  # docker exec -it oracle-xe bash -c "source /home/oracle/.bashrc; bash"
  # /opt/oracle/product/18c/dbhomeXE/bin/sqlplus system/Oracle18@localhost/XE
  # docker exec -it oracle-xe bash -c "/opt/oracle/product/18c/dbhomeXE/bin/sqlplus system/Oracle18@localhost/XE"
  # docker-compose.exe -f .\ubuntu_dev\ubuntu_dev.yml up -d oracle
  oracle:
    image: shchohan/oracle-xe:20200420
    #image: oracle-xe:18c
    container_name: oracle-xe
    domainname: Salah.Chohan
    hostname: oracle
    #command: mount -t vboxsf -o uid=54321,gid=54321 /d/Tools/db/oradata-xe /opt/oracle/oradata
    volumes:
      - /D_DRIVE/Tools/db/oradata-xe:/opt/oracle/oradata
      - /D_DRIVE:/d
      #- /E_DRIVE:/e
    ports:
      - 11521:1521
      - 15500:5500
    environment:
        - TZ=America/Toronto

    networks:
      - accs_net

### Redis   Now redis is running as part ubuntu_dev docker.
  # docker exec -it redis -c "source /home/oracle/.bashrc; bash"
  # redis:
    # image: redis
    # container_name: redis
    # ports:
      # - "6379:6379"

    # deploy:
        # restart_policy:
            # condition: on-failure
            # delay: 5s
            # max_attempts: 3
            # window: 120s
    # dns:
        # - 8.8.8.8
        # - 9.9.9.9

#    entrypoint:
#    healthcheck:
#networks:
#  - ubuntu_dev_net

networks:
  accs_net:
